version: '3'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: ubahn-data-processor-es_zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    container_name: ubahn-data-processor-es_kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      # KAFKA_CREATE_TOPICS: "u-bahn.action.create:1:1,u-bahn.action.update:1:1,u-bahn.action.delete:1:1"
      KAFKA_CREATE_TOPICS: "u-bahn.action.aggregate:1:1,groups.notification.member.add:1:1,groups.notification.member.delete:1:1"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
  esearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.4.2
    container_name: ubahn-data-processor-es_es
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
      - "9300:9300"
